name: Deploy FrontEnd
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t toppo918/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true toppo918/react-test npm test

      

      
